#!/bin/sh

# Some useful tools
git clone https://github.com/srsudar/eg
git clone https://github.com/robbyrussell/oh-my-zsh

# Android SDK
sdkfile="android-sdk_r24.3.2-linux.tgz"
curl http://dl.google.com/android/$sdkfile -O && tar xaf $sdkfile android-sdk-linux && rm $sdkfile

