#!/bin/sh

# Some useful tools
git clone https://github.com/srsudar/eg
git clone https://github.com/robbyrussell/oh-my-zsh

# AUR projects
mkdir build
git clone https://aur.archlinux.org/nerd-fonts-complete.git build/nerd-fonts-complete
git clone https://aur.archlinux.org/polybar.git build/polybar
